language: node_js
dist: xenial
sudo: required
before_install:
- TAG="${TRAVIS_TAG:-latest}"
install:
- curl -fsSL https://get.docker.com | sh
- echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
- mkdir -p $HOME/.docker
- echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
- sudo service docker start
- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- docker buildx create --name xbuilder --use
- echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin &> /dev/null
script:
- docker buildx build --progress plain --platform=linux/amd64,linux/arm64,linux/arm/v7 -t tetrash/openfaas-edge-auth-multiarch:$TAG --push ./edge-auth
- docker buildx build --progress plain --platform=linux/amd64,linux/arm64,linux/arm/v7 -t tetrash/openfaas-edge-router-multiarch:$TAG --push ./edge-router
